Primeiro PR fazendo a instalação do Ubuntu
pagarme/ansible_playbook_qa pull request #1
Opened 2021-07-13 17:53 UTC by btfshadow

Pr tem com o objetivo de colocar as instalações do ansible para Ubuntu 

![image](https://user-images.githubusercontent.com/12503988/125501361-7a5a1daa-40f3-4134-980e-99e9b890bb4c.png)

2021-07-13 18:05 UTC, vannessasoares approved these changes
Para Golang não precisa  instalar nenhuma "dependência"? Eu vi que tem instalações relacionadas a ambiente java, node, python, .netcore etc... só bateu a dúvida mesmo.

2021-07-13 18:58 UTC, PauloGoncalvesBH requested changes

2021-07-13 18:58 UTC, PauloGoncalvesBH commented on README.md
> +'''
```suggestion
```
```
É preciso substituir todos os ''' do documento por ```

2021-07-13 18:58 UTC, PauloGoncalvesBH commented on README.md
> +problary the terminal ask for you sudo password
```suggestion

Problaby the terminal ask for you sudo password
```

2021-07-13 18:58 UTC, PauloGoncalvesBH commented on install-ansible-ubuntu.sh
> +sudo apt install ansible
```suggestion
sudo apt install ansible

```

2021-07-13 18:58 UTC, PauloGoncalvesBH commented on README.md
> +e digite sua senha de 'sudo'
```suggestion
e digite sua senha de `sudo`
```

2021-07-13 18:58 UTC, PauloGoncalvesBH commented on install-linux-ubuntu.yml
> +
```suggestion
```

2021-07-13 18:58 UTC, PauloGoncalvesBH commented on install-linux-ubuntu.yml
> +  - name: Intall docker and update
```suggestion
  - name: Install docker and update
```

2021-07-13 18:58 UTC, PauloGoncalvesBH commented on install-linux-ubuntu.yml
> +  - name: Ensure group "docker" exists with correct gid
```suggestion
  - name: Ensure group "docker" exists with correct GID
```

2021-07-13 18:58 UTC, PauloGoncalvesBH commented on install-linux-ubuntu.yml
> +  - name: Add a Pritul apt key from a keyserver
```suggestion
  - name: Add a Prituln apt key from a keyserver
```

2021-07-13 18:58 UTC, PauloGoncalvesBH commented on install-linux-ubuntu.yml
> +  - name: Intall Pritul and update
```suggestion
  - name: Install Prituln and update
```

2021-07-13 18:58 UTC, PauloGoncalvesBH commented on install-linux-ubuntu.yml
> +
```suggestion
```

2021-07-13 18:58 UTC, PauloGoncalvesBH commented on install-linux-ubuntu.yml
> +      mode: '0755'
O que seria o `0755` em `mode`? Seria interessante adicionar descrevendo o que significa.

2021-07-13 18:58 UTC, PauloGoncalvesBH commented on install-linux-ubuntu.yml
> +      mode: '0755'
Mesma questão do comentário anterior sobre o que é o `0755`.

2021-07-13 18:58 UTC, PauloGoncalvesBH commented on install-linux-ubuntu.yml
> +  - name: instal .NetCore
```suggestion
  - name: Install .NetCore
```

2021-07-13 18:58 UTC, PauloGoncalvesBH commented on install-linux-ubuntu.yml
> +
```suggestion
```

2021-07-13 19:01 UTC, PauloGoncalvesBH requested changes

2021-07-13 19:01 UTC, PauloGoncalvesBH commented on README.md
> +# ANSIBLE PLAYBOOK QA
Listar no README tudo que será instalado e configurado, como `docker`, `zsh`, `docker-compose`, etc. e detalhar se preciso.

2021-07-13 19:16 UTC, PauloGoncalvesBH requested changes
Acredito que seria interessante incluir outras aplicações que usamos no dia a dia, mesmo que em um segundo momento, como:
- git
- node.js > Talvez não precise por boa parte das aplicações estarem dockerizadas
- keybase
- slack
- vsCode

2021-07-13 23:01 UTC, samycici reviewed
eu renomearia o arquivo `install-linux-ubuntu.yml`, pq quando leio ele parece que vai instar o ubuntu hehehehe
sugestão: install-ubuntu-dependencies, ou algo assim

2021-07-14 16:52 UTC, PauloGoncalvesBH requested changes

2021-07-14 16:52 UTC, PauloGoncalvesBH commented on install-ansible-ubuntu.sh
> +sudo apt install ansible
```suggestion
sudo apt install ansible
ansible-playbook install-linux-ubuntu.yml --ask-become-pass
```
O que acha de já colocar a execução do playbook dentro do `.sh` e renomear esse arquivo para algo que referencie que vai instalar as aplicações na máquina windows ao invés de que vai instalar o ansible?

2021-07-14 17:33 UTC, btfshadow commented on install-ansible-ubuntu.sh
> +sudo apt install ansible
Não é uma boa porque vai sempre ficar tentando adicionar o repositório e instalar.

2021-07-14 17:33 UTC, btfshadow commented on README.md
> +# ANSIBLE PLAYBOOK QA
Vou pegar isso.

2021-07-14 17:34 UTC, btfshadow commented on README.md
> +problary the terminal ask for you sudo password
feito

2021-07-14 17:34 UTC, btfshadow commented on README.md
> +'''
feito

2021-07-14 17:35 UTC, btfshadow commented on README.md
> +e digite sua senha de 'sudo'
feito

2021-07-14 17:38 UTC, btfshadow commented on install-linux-ubuntu.yml
> +      mode: '0755'
é a configuração do arquivo, posso até colocar

2021-07-14 17:40 UTC, btfshadow commented on install-linux-ubuntu.yml
> +      mode: '0755'
mas ficaria bem grande

2021-07-14 17:41 UTC, btfshadow commented on install-linux-ubuntu.yml
> +  - name: Add a Pritul apt key from a keyserver
feito

2021-07-14 17:41 UTC, btfshadow commented on install-linux-ubuntu.yml
> +  - name: Intall Pritul and update
feito

2021-07-14 17:41 UTC, btfshadow commented on install-linux-ubuntu.yml
> +
feito

2021-07-14 17:42 UTC, btfshadow commented on install-linux-ubuntu.yml
> +  - name: instal .NetCore
feito

2021-07-14 18:23 UTC, btfshadow commented
> Para Golang não precisa instalar nenhuma "dependência"? Eu vi que tem instalações relacionadas a ambiente java, node, python, .netcore etc... só bateu a dúvida mesmo.

Faz sentido acho que só fugiu mesmo por usar pouco, vou adicionar esse cara.

2021-07-14 18:25 UTC, btfshadow commented
> Acredito que seria interessante incluir outras aplicações que usamos no dia a dia, mesmo que em um segundo momento, como:
> 
> * git
> * node.js > Talvez não precise por boa parte das aplicações estarem dockerizadas
> * keybase
> * slack
> * vsCode

O node tem no nvm, ( que talvez vale um artigo apenas ele ) que é um virtualizador de node, então posso ter varias versões de node na maquina com pouca dificuldade, logo o projeto funciona, o git eu achava que estava vindo junto mas vou adicionar tbm

2021-07-15 14:55 UTC, PauloGoncalvesBH requested changes
Está ótimo Thi :D, as sugestões são apenas pequenos ajustes nos nomes.

2021-07-15 14:55 UTC, PauloGoncalvesBH commented on install-ubuntu-qa-dependencies.yml
> +  - name: Instal GoLang
```suggestion
  - name: Install GoLang
```

2021-07-15 14:55 UTC, PauloGoncalvesBH commented on install-ubuntu-qa-dependencies.yml
> +  - name: Install install Slack
```suggestion
  - name: Install Slack
```

2021-07-15 14:55 UTC, PauloGoncalvesBH commented on install-ubuntu-qa-dependencies.yml
> +  - name: Install install VSCode
```suggestion
  - name: Install VSCode
```

2021-07-15 14:55 UTC, PauloGoncalvesBH commented on install-ubuntu-qa-dependencies.yml
> +  - name: Instal .NetCore
```suggestion
  - name: Install .NetCore
```

2021-07-15 16:53 UTC, vannessasoares requested changes

2021-07-15 16:53 UTC, vannessasoares commented on install-macOS-qa-dependencies.yml
> +  - name: Install Slack
```suggestion
  - name: Install Keybase
```

2021-07-15 16:53 UTC, vannessasoares commented on install-macOS-qa-dependencies.yml
> +  - name: Install Slack
Ai acho que ficou faltando o slack hehe

2021-07-15 17:48 UTC, samycici commented
vou comentar aqui o teste no mac (não desinstalei o que já tinha, só rodei direto o script).
Erros:
`==> Installing python@3.9
==> Pouring python@3.9--3.9.6.catalina.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3
Target /usr/local/bin/2to3
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3'

To force the link and overwrite all conflicting files:
  brew link --overwrite python@3.9

To list all files that would be deleted:
  brew link --overwrite --dry-run python@3.9

Possible conflicting files are:
/usr/local/bin/2to3 -> /Library/Frameworks/Python.framework/Versions/3.8/bin/2to3
/usr/local/bin/idle3 -> /Library/Frameworks/Python.framework/Versions/3.8/bin/idle3
/usr/local/bin/pydoc3 -> /Library/Frameworks/Python.framework/Versions/3.8/bin/pydoc3
/usr/local/bin/python3 -> /Library/Frameworks/Python.framework/Versions/3.8/bin/python3
/usr/local/bin/python3-config -> /Library/Frameworks/Python.framework/Versions/3.8/bin/python3-config
`

2021-07-15 17:54 UTC, samycici commented
> vou comentar aqui o teste no mac (não desinstalei o que já tinha, só rodei direto o script então muitas coisas já estavam instaladas).
> Erros:
> `==> Installing python@3.9 ==> Pouring python@3.9--3.9.6.catalina.bottle.tar.gz Error: The `brew link` step did not complete successfully
> The formula built, but is not symlinked into /usr/local
> Could not symlink bin/2to3
> Target /usr/local/bin/2to3
> already exists. You may want to remove it:
> rm '/usr/local/bin/2to3'
> 
> To force the link and overwrite all conflicting files:
> brew link --overwrite python@3.9
> 
> To list all files that would be deleted:
> brew link --overwrite --dry-run python@3.9
> 
> Possible conflicting files are:
> /usr/local/bin/2to3 -> /Library/Frameworks/Python.framework/Versions/3.8/bin/2to3
> /usr/local/bin/idle3 -> /Library/Frameworks/Python.framework/Versions/3.8/bin/idle3
> /usr/local/bin/pydoc3 -> /Library/Frameworks/Python.framework/Versions/3.8/bin/pydoc3
> /usr/local/bin/python3 -> /Library/Frameworks/Python.framework/Versions/3.8/bin/python3
> /usr/local/bin/python3-config -> /Library/Frameworks/Python.framework/Versions/3.8/bin/python3-config
> `

finalizou com esse erro aqui: 

`WARNING: The directory '/Users/samantacicilia/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: You are using pip version 20.0.2; however, version 21.1.3 is available.
You should consider upgrading via the '/usr/local/bin/python3.8 -m pip install --upgrade pip' command.
Starting galaxy collection install process
Process install dependency map
ERROR! Unknown error when attempting to call Galaxy at 'https://galaxy.ansible.com/api/': <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>`

2021-07-15 19:14 UTC, btfshadow commented on install-macOS-qa-dependencies.yml
> +  - name: Install Slack
hehehe pulei esse

2021-07-16 11:34 UTC, dayaneCsantos commented on install-ansible-ubuntu.sh
> +ansible-galaxy collection install community.general
Faltou uma linha a mais ao final

2021-07-16 13:39 UTC, vannessasoares approved these changes

2021-07-16 17:08 UTC, PauloGoncalvesBH approved these changes

2021-07-16 17:09 UTC, PauloGoncalvesBH requested changes

2021-07-16 17:09 UTC, PauloGoncalvesBH commented on README.md
> +- circleci(validade)
```suggestion
- circleci (validate)
```

2021-07-16 19:58 UTC, PauloGoncalvesBH approved these changes

2021-07-16 20:40 UTC, merged